# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - storage:/app/storage
    tmpfs:
      - /tmp
      - /app/tmp/pids
    environment:
      RAILS_ENV: development
      DATABASE_HOST: database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: my_etm_development
    depends_on:
      database:
        condition: service_healthy
    command: bundle exec rails server -b 0.0.0.0

  database:
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_etm_development
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  bundle:
  db_data:
  node_modules:
  rails_cache:
  storage:
