require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/saved_scenarios", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SavedScenario. As you add validations to SavedScenario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      title: 'Baking a scenario',
      scenario_id: 1234,
      end_year: 2050,
      area_code: 'nl2019'
    }
  }

  let(:invalid_attributes) {
    {
      title: 'Baking a scenario',
      scenario_id: 'hello'
    }
  }

  let(:user) { FactoryBot.create(:user) }
  let!(:user_scenario) { FactoryBot.create(:saved_scenario, id: 648695, user: user) }
  let(:admin) { FactoryBot.create :admin }
  let!(:admin_scenario) { FactoryBot.create :saved_scenario, user: admin, id: 648696 }


  describe "GET /index" do
    before do
      sign_in(user)
      user_scenario
    end

    it "renders a successful response" do
      get saved_scenarios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    context 'without a user signed in' do
      it "renders a successful response" do
        get saved_scenario_url(user_scenario)
        expect(response).to be_successful
      end
    end

    context 'when a user is signed in' do
      before { sign_in(user) }
      it "renders a successful response" do
        get saved_scenario_url(user_scenario)
        expect(response).to be_successful
      end
    end
  end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_saved_scenario_url
  #     expect(response).to be_successful
  #   end
  # end

  describe "GET /edit" do
    before { sign_in(user) }

    it "renders a successful response" do
      get edit_saved_scenario_url(user_scenario)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    before { sign_in(user) }

    context "with valid parameters" do
      it "creates a new SavedScenario" do
        expect {
          post(saved_scenarios_url, params: { saved_scenario: valid_attributes })
        }.to change(SavedScenario, :count).by(1)
      end

      it "redirects to the created saved_scenario" do
        post saved_scenarios_url, params: { saved_scenario: valid_attributes }
        expect(response).to redirect_to(saved_scenario_url(SavedScenario.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SavedScenario" do
        expect {
          post(saved_scenarios_url, params: { saved_scenario: invalid_attributes })
        }.to change(SavedScenario, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post saved_scenarios_url, params: { saved_scenario: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    before { sign_in(user) }

    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested saved_scenario" do
        patch saved_scenario_url(user_scenario), params: { saved_scenario: new_attributes }
        user_scenario.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the saved_scenario" do
        patch saved_scenario_url(user_scenario), params: { saved_scenario: new_attributes }
        user_scenario.reload
        expect(response).to redirect_to(saved_scenario_url(saved_scenario))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch saved_scenario_url(user_scenario), params: { saved_scenario: invalid_attributes }
        expect(response).to have_http_status(:found)
      end
    end
  end

  describe "DELETE /destroy" do
    before { sign_in(user) }

    it "destroys the requested saved_scenario" do
      expect {
        delete(saved_scenario_url(user_scenario))
      }.to change(SavedScenario, :count).by(-1)
    end

    it "redirects to the trash can" do
      delete saved_scenario_url(user_scenario)
      expect(response).to redirect_to(discarded_url)
    end
  end

  describe 'PUT /publish' do
    before do
      sign_in(user)
      allow(ApiScenario::UpdatePrivacy).to receive(:call_with_ids)
    end

    context 'with an owned saved scenario' do
      before do
        user_scenario.update!(private: true)
        put publish_saved_scenario_url(user_scenario)
      end

      it 'redirects to the scenario' do
        expect(response).to be_redirect
      end

      it 'makes the scenario public' do
        expect(user_scenario.reload).not_to be_private
      end

      pending 'updates the API scenarios' do
        expect(ApiScenario::UpdatePrivacy).to have_received(:call_with_ids).with(
          anything, [user_scenario.id], private: false
        )
      end
    end

    context 'with an unowned saved scenario' do
      before do
        admin_scenario.update!(private: true)
        put publish_saved_scenario_url(admin_scenario)
      end

      it 'returns 404' do
        expect(response).to be_not_found
      end

      it 'does not change the scenario privacy' do
        expect(admin_scenario.reload).to be_private
      end

      it 'does not update the API scenarios' do
        expect(ApiScenario::UpdatePrivacy).not_to have_received(:call_with_ids)
      end
    end
  end

  describe 'PUT /unpublish' do
    before do
      sign_in(user)
      allow(ApiScenario::UpdatePrivacy).to receive(:call_with_ids)
    end

    context 'with an owned saved scenario' do
      before do
        user_scenario.update!(private: false)
        put unpublish_saved_scenario_url(user_scenario)
      end

      it 'redirects to the scenario listing' do
        expect(response).to be_redirect
      end

      it 'makes the scenario public' do
        expect(user_scenario.reload).to be_private
      end

      pending 'updates the API scenarios' do
        expect(ApiScenario::UpdatePrivacy).to have_received(:call_with_ids).with(
          anything, [user_scenario.id], private: true
        )
      end
    end

    context 'with an unowned saved scenario' do
      before do
        user_scenario.update!(private: false)
        put unpublish_saved_scenario_url(admin_scenario)
      end

      it 'returns 404' do
        expect(response).to be_not_found
      end

      it 'does not change the scenario privacy' do
        expect(admin_scenario.reload).not_to be_private
      end

      it 'does not update the API scenarios' do
        expect(ApiScenario::UpdatePrivacy).not_to have_received(:call_with_ids)
      end
    end
  end
end
