# frozen_string_literal: true

# The token contract between MyETM and every app that verifies its tokens.
#
# MyETM mints the tokens; ETEngine, ETModel and Collections verify them, in two separate
# implementations (Identity::TokenDecoder in Ruby, jose in Collections). Nothing in the code keeps
# the minting and the verifying in step — a change here is only felt in another repo, at runtime.
# That is exactly how the `kid` and `aud` breaks got as far as they did.
#
# So this spec pins the contract and writes it to a fixture the consumers verify against:
#
#   REGENERATE_TOKEN_CONTRACT=1 bundle exec rspec spec/requests/token_contract_spec.rb
#
# then copy spec/fixtures/token_contract.json to:
#   - identity_rails/spec/fixtures/token_contract.json   (covers ETEngine and ETModel)
#   - multi-year-charts/__fixtures__/token_contract.json (covers Collections)
#
# If a consumer's suite goes red after regenerating, the change is breaking — that is the point.
RSpec.describe 'Token contract', type: :request do
  let(:user) { create(:user, :confirmed_at) }

  before { Version.default }

  let(:anchor) do
    user.access_tokens.create!(
      expires_in: JwtSessionCookies::ACCESS_TTL,
      scopes: JwtSessionCookies::SESSION_SCOPES,
      use_refresh_token: true
    )
  end

  let(:session_claims) do
    payload, = JWT.decode(
      anchor.token, MyEtm::Auth.signing_key.public_key, true, algorithms: ['RS256']
    )
    payload
  end

  let(:session_header) do
    JWT.decode(anchor.token, nil, false).last
  end

  describe 'the session token' do
    it 'is signed with RS256' do
      expect(session_header['alg']).to eq('RS256')
    end

    it 'names its key with the kid published at /oauth/discovery/keys' do
      expect(session_header['kid']).to eq(Doorkeeper::OpenidConnect.signing_key.kid)
    end

    it 'carries the claims every consumer requires' do
      expect(session_claims).to include('iss', 'aud', 'sub', 'exp', 'scopes', 'user')
    end

    it 'is issued by MyETM' do
      expect(session_claims['iss']).to eq(Settings.auth.issuer)
    end

    it 'has an array audience, not a space-delimited string' do
      expect(session_claims['aud']).to be_a(Array)
    end

    it 'is audienced at every ETM app and at MyETM itself' do
      expect(session_claims['aud'])
        .to include(*Version.default.urls, Settings.auth.issuer)
    end

    it 'identifies the user by database id' do
      expect(session_claims['sub']).to eq(user.id)
    end
  end

  describe 'the JWKS' do
    subject(:keys) do
      get '/oauth/discovery/keys'
      JSON.parse(response.body)['keys']
    end

    it 'resolves the session token’s kid' do
      expect(keys.map { |key| key['kid'] }).to include(session_header['kid'])
    end
  end

  it 'writes the fixture when REGENERATE_TOKEN_CONTRACT is set' do
    skip 'set REGENERATE_TOKEN_CONTRACT=1 to rewrite the fixture' unless ENV['REGENERATE_TOKEN_CONTRACT']

    get '/oauth/discovery/keys'

    path = Rails.root.join('spec/fixtures/token_contract.json')
    path.dirname.mkpath
    path.write(JSON.pretty_generate(
      'README' => 'Generated by my-etm spec/requests/token_contract_spec.rb. Do not edit by hand.',
      'generated_at' => Time.current.to_i,
      'issuer' => Settings.auth.issuer,
      'jwks' => JSON.parse(response.body),
      'session_token' => anchor.token,
      'session_audience' => session_claims['aud'],
      # A token in the pre-migration shape: legacy kid, space-delimited audience string. Consumers
      # must still verify this until the next major API break invalidates every pre-migration PAT,
      # at which point OAuth::DiscoveryController#legacy_key and TokenDecoder#verify_audience!'s
      # `.split` can be removed together.
      'legacy_token' => legacy_shaped_token
    ))

    expect(path).to exist
  end

  # Reproduces exactly how MyETM used to mint tokens, so consumers can prove their transitional
  # handling works rather than assuming it.
  def legacy_shaped_token
    key = MyEtm::Auth.signing_key
    JWT.encode(
      session_claims.merge('aud' => session_claims['aud'].join(' ')),
      key,
      'RS256',
      kid: JWT::JWK.new(key.public_key).export[:kid]
    )
  end
end
