default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', nil) %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 3306) %>

development:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'my_etm_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'my_etm_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'my_etm_production') %>
