default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: <%= ENV['DATABASE_HOST'].present? ? nil : '/tmp/mysql.sock' %>

development: &development
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'my_etm_development') %>
  host: <%= ENV.fetch('DATABASE_HOST', nil) %>
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', nil) %>

test:
  <<: *development
  database: my_etm_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
