
etmodel:
  uri: http://localhost:3001
etengine:
  uri: http://localhost:3000

myetm:
  iss: my-etm
  uri: <%= ENV.fetch('OPENID_ISSUER', 'http://localhost:3002') %>

collections_url: <%= ENV.fetch('COLLECTIONS_URL', 'http://localhost:3005') %>

mailchimp:
  newsletter:
    list_url: <%= ENV.fetch('MAILCHIMP_LIST_URL', nil) %>
    api_key: <%= ENV.fetch('MAILCHIMP_API_KEY', nil) %>
  changelog:
    list_url: <%= ENV.fetch('MAILCHIMP_LIST_CHANGELOG_URL', nil) %>
    api_key: <%= ENV.fetch('MAILCHIMP_API_KEY', nil) %>

# set to true if the server won't have online access. this disables Sentry,
# etc.
standalone: false

mailer:
  # E-mail address from which to send e-mails.
  from: "Energy Transition Model <info@energytransitionmodel.com>"

auth:
  issuer: <%= ENV.fetch('OPENID_ISSUER', 'http://localhost:3002') %>
