# Staff applications – local devlopment
etmodel:
  uri: http://localhost:3001
etengine:
  uri: http://localhost:3000
collections:
  uri: http://localhost:3005

myetm:
  iss: my-etm
  uri: <%= ENV.fetch('OPENID_ISSUER', 'http://localhost:3002') %>

mailchimp:
  newsletter:
    list_url: <%= ENV.fetch('MAILCHIMP_LIST_URL', nil) %>
    api_key: <%= ENV.fetch('MAILCHIMP_API_KEY', nil) %>
  changelog:
    list_url: <%= ENV.fetch('MAILCHIMP_LIST_CHANGELOG_URL', nil) %>
    api_key: <%= ENV.fetch('MAILCHIMP_API_KEY', nil) %>

recaptcha:
  site_key:  <%= ENV.fetch('RECAPTCHA_SITE_KEY', nil) %>
  secret_key: <%= ENV.fetch('RECAPTCHA_SECRET_KEY', nil) %>

# set to true if the server won't have online access. this disables Sentry,
# etc.
standalone: false

mailer:
  # E-mail address from which to send e-mails.
  from: "Energy Transition Model <info@energytransitionmodel.com>"

auth:
  issuer: <%= ENV.fetch('OPENID_ISSUER', 'http://localhost:3002') %>

# Optionally send error messages to the Sentry service by providing your
# Sentry DSN:
sentry_dsn: <%= ENV['SENTRY_DSN'] %>
