# Directory where ETSource revisions will be exported.
etsource_export: "../etsource"

# The path where the ETSource Git repository can be found.
etsource_working_copy: "../etsource"

# If for some reason you don't want to clear the etsource_export directory
etsource_disable_export: false

# Enables "live" reloading of the ETSource export. When enabled, changes to datasets/, gqueries/,
# inputs/, and topology/ will be detected and ETSource will expire its cached copy. The files will
# be reloaded the on the next request.
#
# Note that this setting only applies to the development environment; live reloading is always
# disabled in production and test environments.
etsource_live_reload: true

# Enables lazy loading of datasets from Refinery.
#
# With this disabled, MyETM will expect that tmp/atlas contains YML files for each region. These
# are created by Atlas during a production deployment, or when changing the loaded version of
# ETESource in the admin interface.
#
# When enabled, MyETM will load Atlas and Refinery, and calculate the graph in Refinery the first
# time you load a scenario for the region. This is preferable for development environments, when you
# don't want to have to worry about creating the YML files manually.
etsource_lazy_load_dataset: true

# URL to be called after a clean etsource import Usually you would set something like
# http://beta.et-model.com/pages/refresh_gqueries
client_refresh_url:

# TODO: Fix this to fetch from ENV
etmodel:
  uri: http://localhost:3001
etengine:
  uri: http://localhost:3000
collections:
  uri: http://localhost:3005
myetm:
  iss: my-etm
  uri: http://localhost:3002

identity:
  token_exchange_url: http://localhost:3002/identity/token_exchange

# set to true if the server won't have online access. this disables Sentry,
# etc.
standalone: false

mailer:
  # E-mail address from which to send e-mails.
  from: "Energy Transition Model <info@energytransitionmodel.com>"

auth:
  issuer: <%= ENV.fetch('OPENID_ISSUER', 'http://localhost:3002') %>

# Optional settings to configure the Mailchimp integration.
mailchimp:
  list_url: <%= ENV.fetch('MAILCHIMP_LIST_URL', nil) %>
  api_key: <%= ENV.fetch('MAILCHIMP_API_KEY', nil) %>
